language: node_js
node_js:
  - "stable"
  - "node"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
env:
  - CXX=g++-4.8
cache:
  directories:
    - "node_modules"
script:
  - npm run all
after_success:
  - npm run coveralls
