language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libasound2-dev
      - g++-4.8
cache:
  directories:
    - "node_modules"
script:
  - npm run travis
after_success:
  - npm run coveralls
